### PR TITLE
Added samples restaurants of Campinas to use OCR

### PR DESCRIPTION
**Pull request by gportog**
First samples search to apply OCR. 

Signed-off-by: Gustavo Guedes gustavo.guedes@br.ibm.com

### CODE REVIEW

**Comment by gabrieldrs** [comment]
hey Gustavo, could you please resend your commit? I had to rewrite the commit history (clean up the commits we did in our last meeting) and because of that you will have to rewrite yours (sorry).

An easy way to do it is to:

1. create a patch with your last commit
A patch is a "bucket" of changes you organize in a file, in order to create a patch for your last commit type:
```
git format-patch -1 HEAD
```
This will create a file called 0001-Add samples restaurants [...]

2. Then fetch changes from the official repository: `git fetch official`
3. Reset your branch to be the same as the official: `git reset --hard remotes/official/master`
4. Apply saved patch: `git am -3 0001-Add samples restaurants [...]`, you should not receive any conflict.
5. Push to your fork: `git push fork master`

You don't need to open another Pull Request, updating your fork updates this PR automatically.

**Comment by gportog** [comment]
Got it! I'll try it out! 
tks!

**Comment by gabrieldrs** [comment]
Hnn... Now that I see it, you had pushed your code to a separate branch called "add_samples_campinas", so you have to push to this branch instead (If you did this reset/patch process in you master branch, you can do that with `git push my_fork master:add_samples_campinas`, you may need to use --force in order to rewrite the history).

**Comment by gportog** [comment]
@gabrieldrs could you take a look to see if the result is right:
```
[gportog@oc0734426640 TOP-The-OCR-Project]$ git branch
* add_samples_campinas
  add_tesseract
  master

[gportog@oc0734426640 TOP-The-OCR-Project]$ git push my_fork master:add_samples_campinas --force
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/gportog/TOP-The-OCR-Project.git
 + 7053c51...bed1bb9 master -> add_samples_campinas (forced update)

```

**Pull request merged**
